import React, { useState } from 'react';
import { useApp } from '../context/AppContext';
import { 
  ShieldAlert, 
  Search,
  ChevronRight
} from 'lucide-react';
import { AlertStatus } from '../types';

export const AlertsInvestigationView: React.FC = () => {
  const { alerts, updateAlertStatus, inspectRec, addToast } = useApp();

  const [severityFilter, setSeverityFilter] = useState<string>('ALL');
  const [statusFilter, setStatusFilter] = useState<string>('ALL');
  const [searchTerm, setSearchTerm] = useState('');

  const filteredAlerts = alerts.filter(a => {
    const sev = a.severity || a.riskBand;
    if (severityFilter !== 'ALL' && sev !== severityFilter) return false;
    if (statusFilter !== 'ALL' && a.status !== statusFilter) return false;
    if (searchTerm.trim()) {
      const q = searchTerm.toLowerCase();
      const title = a.title || a.alertType;
      const desc = a.description || a.summary;
      return (
        a.id.toLowerCase().includes(q) ||
        a.recId.toLowerCase().includes(q) ||
        title.toLowerCase().includes(q) ||
        desc.toLowerCase().includes(q)
      );
    }
    return true;
  });

  const handleStatusChange = (alertId: string, newStatus: AlertStatus) => {
    updateAlertStatus(alertId, newStatus);
    addToast({
      type: 'info',
      title: 'Alert Status Updated',
      message: `Alert ${alertId} marked as ${newStatus}.`
    });
  };

  const criticalCount = alerts.filter(a => (a.severity || a.riskBand) === 'CRITICAL').length;
  const highCount = alerts.filter(a => (a.severity || a.riskBand) === 'HIGH').length;

  return (
    <div className="p-4 md:p-6 space-y-6 max-w-[1600px] mx-auto animate-in fade-in duration-300">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-800 pb-4">
        <div>
          <h1 className="text-xl md:text-2xl font-bold text-slate-100 flex items-center gap-2">
            <ShieldAlert className="w-6 h-6 text-rose-400" />
            <span>Market Integrity Alerts & Forensic Triage</span>
          </h1>
          <p className="text-xs text-slate-400">
            Real-time audit alerts generated by deterministic rules, statistical thresholds, and the Isolation Forest pipeline.
          </p>
        </div>

        <div className="flex items-center gap-2 font-mono text-xs">
          <span className="px-2.5 py-1 rounded bg-rose-500/20 text-rose-300 border border-rose-500/40 font-bold">
            {criticalCount} CRITICAL
          </span>
          <span className="px-2.5 py-1 rounded bg-orange-500/20 text-orange-300 border border-orange-500/40 font-bold">
            {highCount} HIGH
          </span>
        </div>
      </div>

      {/* Filter toolbar */}
      <div className="p-4 rounded-xl bg-slate-900/80 border border-slate-800/90 flex flex-wrap items-center justify-between gap-3 text-xs">
        <div className="flex flex-wrap items-center gap-3 flex-1 min-w-[280px]">
          <div className="relative flex-1 min-w-[200px]">
            <input
              type="text"
              placeholder="Search alert, REC ID, or forensic keyword..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full bg-slate-950 border border-slate-800 rounded-lg pl-8 pr-3 py-1.5 text-xs text-slate-200 placeholder-slate-500 focus:outline-none focus:border-emerald-500"
            />
            <Search className="w-3.5 h-3.5 text-slate-500 absolute left-2.5 top-2" />
          </div>

          <select
            value={severityFilter}
            onChange={(e) => setSeverityFilter(e.target.value)}
            className="bg-slate-950 border border-slate-800 rounded-lg px-2.5 py-1.5 text-xs text-slate-200 focus:outline-none"
          >
            <option value="ALL">All Severities</option>
            <option value="CRITICAL">Critical</option>
            <option value="HIGH">High</option>
            <option value="MEDIUM">Medium</option>
            <option value="LOW">Low</option>
          </select>

          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            className="bg-slate-950 border border-slate-800 rounded-lg px-2.5 py-1.5 text-xs text-slate-200 focus:outline-none"
          >
            <option value="ALL">All Triage Statuses</option>
            <option value="OPEN">Open</option>
            <option value="UNDER_REVIEW">Under Review</option>
            <option value="RESOLVED">Resolved</option>
            <option value="ESCALATED">Escalated</option>
          </select>
        </div>

        <span className="text-slate-400 font-mono text-[11px]">
          Showing {filteredAlerts.length} of {alerts.length} alerts
        </span>
      </div>

      {/* Alerts Stream */}
      <div className="space-y-3">
        {filteredAlerts.map(alert => {
          const sev = alert.severity || alert.riskBand;
          const title = alert.title || `${alert.alertType} Flagged`;
          const desc = alert.description || alert.summary || (alert.evidence && alert.evidence[0]) || 'Audit review flagged';
          const time = alert.timestamp || alert.detectedAt;

          return (
            <div
              key={alert.id}
              className={`p-5 rounded-2xl border transition-all ${
                sev === 'CRITICAL' ? 'bg-rose-950/20 border-rose-500/40 hover:border-rose-500' :
                sev === 'HIGH' ? 'bg-orange-950/20 border-orange-500/30 hover:border-orange-500' :
                'bg-slate-900/60 border-slate-800 hover:border-slate-700'
              }`}
            >
              <div className="flex flex-col md:flex-row md:items-start justify-between gap-4">
                
                {/* Alert title and metadata */}
                <div className="space-y-2 flex-1">
                  <div className="flex flex-wrap items-center gap-2 font-mono text-xs">
                    <span className={`px-2 py-0.5 rounded font-bold ${
                      sev === 'CRITICAL' ? 'bg-rose-600 text-white' :
                      sev === 'HIGH' ? 'bg-orange-600 text-white' :
                      'bg-slate-800 text-slate-300'
                    }`}>
                      {sev}
                    </span>
                    <span className="font-bold text-slate-200">{alert.id}</span>
                    <span className="text-slate-500">•</span>
                    <button
                      onClick={() => inspectRec(alert.recId)}
                      className="text-emerald-400 hover:underline font-bold"
                    >
                      {alert.recId}
                    </button>
                    <span className="text-slate-500">•</span>
                    <span className="text-slate-400 text-[11px]">{time}</span>
                  </div>

                  <h3 className="text-sm md:text-base font-bold text-slate-100">{title}</h3>
                  <p className="text-xs text-slate-300 leading-relaxed font-sans max-w-4xl">
                    {desc}
                  </p>

                  {alert.assignedAuditor && (
                    <div className="text-[11px] font-mono text-slate-400 pt-1">
                      ASSIGNED TO: <span className="text-indigo-300 font-semibold">{alert.assignedAuditor}</span>
                    </div>
                  )}
                </div>

                {/* Status & Actions */}
                <div className="flex flex-col items-end gap-3 shrink-0">
                  <div className="flex items-center gap-2">
                    <span className={`text-[10px] font-mono px-2 py-0.5 rounded font-bold ${
                      alert.status === 'OPEN' ? 'bg-rose-500/20 text-rose-300' :
                      alert.status === 'UNDER_REVIEW' || alert.status === 'IN_REVIEW' ? 'bg-amber-500/20 text-amber-300' :
                      alert.status === 'ESCALATED' ? 'bg-purple-500/20 text-purple-300' :
                      'bg-emerald-500/20 text-emerald-300'
                    }`}>
                      {alert.status}
                    </span>
                  </div>

                  {/* Triage controls */}
                  <div className="flex flex-wrap items-center gap-1.5">
                    {alert.status !== 'UNDER_REVIEW' && (
                      <button
                        onClick={() => handleStatusChange(alert.id, 'UNDER_REVIEW')}
                        className="px-2.5 py-1 rounded bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-semibold"
                      >
                        In Review
                      </button>
                    )}
                    {alert.status !== 'ESCALATED' && (
                      <button
                        onClick={() => handleStatusChange(alert.id, 'ESCALATED')}
                        className="px-2.5 py-1 rounded bg-rose-500/20 hover:bg-rose-500/30 text-rose-300 text-xs font-semibold"
                      >
                        Escalate
                      </button>
                    )}
                    {alert.status !== 'RESOLVED' && (
                      <button
                        onClick={() => handleStatusChange(alert.id, 'RESOLVED')}
                        className="px-2.5 py-1 rounded bg-emerald-500/20 hover:bg-emerald-500/30 text-emerald-300 text-xs font-semibold"
                      >
                        Resolve
                      </button>
                    )}
                    <button
                      onClick={() => inspectRec(alert.recId)}
                      className="px-3 py-1 rounded bg-emerald-600 hover:bg-emerald-500 text-slate-950 text-xs font-bold flex items-center gap-1 transition-transform active:scale-95"
                    >
                      <span>Dossier</span>
                      <ChevronRight className="w-3.5 h-3.5" />
                    </button>
                  </div>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};
